/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bc2019.zmj2;

import bc2019.zmj2.util.AuthException;
import bc2019.zmj2.util.Util;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String[] args) {
    	try {
			Util.signUp("johndoe@email.com", "123456");
		} catch (AuthException e) {
			e.printStackTrace();
		}
    }
}
